name: Daily Commit

on: [ workflow_dispatch ]
  schedule:
    # 毎日午前1時に実行
    - cron: "0 1 * * *"

jobs:
  commit_and_push:
    runs-on: ubuntu-latest

    steps:
    # リポジトリをチェックアウト
    - name: Check out repository
      uses: actions/checkout@v3

    # 任意のファイル変更（例: タイムスタンプを更新）
    - name: Update timestamp
      run: |
        echo "Last run: $(date)" > timestamp.txt

    # 変更をGitにコミット
    - name: Commit changes
      run: |
        git config --global user.name "427harinn"
        git config --global user.email "rinnrenn424@yahoo.co.jp"
        git add .
        git commit -m "Automated daily commit"

    # リモートにプッシュ
    - name: Push changes
      run: |
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
